Pandas is the fundamental Python Library for data manupulation,analysing and cleaning the data. It provides high-performance data structure like DataFrame and Series,operating like an in-memory SQL database or Excel spreadsheet.

Pandas is built on two main data structures: Series and DataFrames

# Series
A Series in pandas is one dimentional arry with labels(Index for each value).
Series= Data + label(index like names for each value)
it consists of single Column.

In [1]:
import pandas as pd
import numpy as np
#create from list
s=pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [2]:
df=pd.Series([1,2,3,'ram'])
df

0      1
1      2
2      3
3    ram
dtype: object

In [3]:
data=pd.Series([1,2,3,4],index=['a','b','c','d'])
print(data)

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
df=pd.Series([2,3,4,5,6.7,8.9,"ram","seetha",{"name":'seetha'}])
df

0                     2
1                     3
2                     4
3                     5
4                   6.7
5                   8.9
6                   ram
7                seetha
8    {'name': 'seetha'}
dtype: object

In [5]:
names=pd.Series(['Sitha','Chand','Ram'])
print(names[1])
names

Chand

0    Sitha
1    Chand
2      Ram
dtype: object

In [6]:
#Creating Series using list and assigning index
s_list=pd.Series([34,25,6,7],index=['a','b','c','d'])
print(s_list)
print(f"1st: {s_list['a']}") #calling the s_list for finding the value's position using index 
print(f"2nd: {s_list['d']}")

a    34
b    25
c     6
d     7
dtype: int64
1st: 34
2nd: 7

In [7]:
data=pd.Series([30,45,49],index=['maths','science','chemistry'])
data

maths        30
science      45
chemistry    49
dtype: int64

In [8]:
#using dictionary
dict={'a':10,'b':20,'c':30}
p=pd.Series(dict,index=[0,1,2])# Pandas tries to match index values with dict values ,since 0,1,2 are not in dict, values become NaN
p

0   NaN
1   NaN
2   NaN
dtype: float64

In [9]:
dict={'a':10,'b':20,'c':30}
p=pd.Series(dict)
p

a    10
b    20
c    30
dtype: int64

# DataFrame
Data is 2-Dimentional labeled data structure with columns of potential different types(like SQL and Excel sheets) which consists of rows and columns

In [10]:
#Within the DataFrame no need to add the index, index can only be used if there is in specification required for the index 
data={
    'Name':['Ram','Sita','chand','lohit'],
    'age':[25,30,28,31],
    'city':['Bangalore','Chennai','Hydrabad','Bangalore']     
}
df=pd.DataFrame(data)
print(df)

    Name  age       city
0    Ram   25  Bangalore
1   Sita   30    Chennai
2  chand   28   Hydrabad
3  lohit   31  Bangalore

In [11]:
# From dict of lists(most common)
data=pd.DataFrame({
    'Name':['ram','seetha'],
    'Age':[29,25]
})
print(data)

     Name  Age
0     ram   29
1  seetha   25

In [12]:
frames=pd.DataFrame({
    "Names":["Ram","Charan","Praveen"],
    'Age':[20,19,21],
    "Marks":[45,43,42]
})
frames

     Names  Age  Marks
0      Ram   20     45
1   Charan   19     43
2  Praveen   21     42

In [13]:
df=pd.DataFrame({
    'Name':['Ravi','Raji','Chanz'],
    'Marks':[34,50,50]
})
print(df)

    Name  Marks
0   Ravi     34
1   Raji     50
2  Chanz     50

In [14]:
#from list of dictonaries
data=[
    {'Name':'Ravi','age':25},
    {'Name':'Vikitha','age':26}
]
data=pd.DataFrame(data,index=['a','b'])
print(data)

      Name  age
a     Ravi   25
b  Vikitha   26

In [15]:
#from list of lists
data=[
    ['Praveen',34],
    ['charan',25]
]
df=pd.DataFrame(data,columns=['Name','age'])
print(df)

      Name  age
0  Praveen   34
1   charan   25

In [16]:
#from list to list
names=[
     ['ram',20],
      ['janaki',19]
]
df=pd.DataFrame(names,columns=['Name','Age'])
print(df)

     Name  Age
0     ram   20
1  janaki   19

In [17]:
df=pd.DataFrame([['Ram',25],['Janaki',30]],index=['Husband','Wife'],columns=['Name','Relationship'])
print(df)

           Name  Relationship
Husband     Ram            25
Wife     Janaki            30

In [18]:
column=pd.DataFrame([["Rani",19,"bangalore"],["Raju",18,"Chennai"],["Ravi",20,"Bangalore"],["Ram",19,"kerala"]],columns=["Name","Age","City"])
column

   Name  Age       City
0  Rani   19  bangalore
1  Raju   18    Chennai
2  Ravi   20  Bangalore
3   Ram   19     kerala

In [19]:
# From Numpy Array
arr=np.array([[2,3],[3,4]])
df=pd.DataFrame(arr,columns=['A','B'])
print(df)

   A  B
0  2  3
1  3  4

In [20]:
#From Dictionary of Series
s1=pd.Series([1,2])
s2=pd.Series([3,4])

df=pd.DataFrame({"col1": s1,"col2": s2})
df

   col1  col2
0     1     3
1     2     4

In [21]:
s1=pd.Series(["Raju","Rani","Navin","Lohit"])
s2=pd.Series([23,34,48,44,50])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad"])
data=pd.DataFrame({"Name":s1,"Age":s2,"city":s3})
data

    Name  Age       city
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad
4    NaN   50        NaN

In [22]:
#Create DataFrame within the code
df=pd.DataFrame({
    "Name":["Ram","Chanz"],
    "Age":[20,30]
})
df

    Name  Age
0    Ram   20
1  Chanz   30

# Reading And Writing the Data

Pandas makes extreamly easy to lead and read the data from various sources and save it back out.

Reading the data

In [ ]:
df_csv=pd.read_csv('data.csv')
df_excel=pd.read_excel('data.excel')
df_json=pd.read_json('data.json')
df_sql=pd.read_sql("SELECT * FROM users",con=db_connection)

Tip: pd.read_csv() has dozens of parameters to handle broken data(eg., sep, na_values, parse_dates, encoding)

# Writing the data

In [ ]:
df.to_csv('cleaned_data_csv',index=False)
df.to_excel('output_xlsv',index=False)

# Understanding the loded data#

In [ ]:
df.head(5)     # view first 5 rows
df.tail(5)     # view last 5 rows
df.info()      # Data types,non-null counts, and memory usage
df.describe()  # stastical summary like count,min,max,std, and quartile
df.shape       # Tuple of (rows, columns)
df.columns     # list of column names
df.dtype       # data type of each columns

# Selecting and filetering data

Pandas provides multiple ways to slice and dice your data.

In [ ]:
#Selecting Columns
names=df['Name']  # Returns a Series 
subset=df[['Name','Age']]  # Returns a DataFrame

In [ ]:
# Example
df=pd.DataFrame({
    "Name":["Ram","Chanz"],
    "Age":[20,30]
})
names=df['Name']  # Returns a Series 
print(names)
subset=df[['Name','Age']]  # Returns a DataFrame  
print(subset)

0      Ram
1    Chanz
Name: Name, dtype: object
    Name  Age
0    Ram   20
1  Chanz   30

# Selecting Rows by label(.loc)
# Selecting Rows by Position (.iloc)

In [ ]:
df = pd.DataFrame({
    "Name": ["Ram", "Sita", "Hari"],
    "Age": [25, 30, 22]
})
print(df)
print(f"\nFirst Row:{df.loc[0]}")
df.loc[1]

   Name  Age
0   Ram   25
1  Sita   30
2  Hari   22

First Row:Name    Ram
Age      25
Name: 0, dtype: object

Name    Sita
Age       30
Name: 1, dtype: object

In [ ]:
df = pd.DataFrame({
    "Name": ["Ram", "Sita", "Hari"],
    "Age": [25, 30, 22]
})
print(df)
df.iloc[1,0] #it selects fisrt row and 0 column

   Name  Age
0   Ram   25
1  Sita   30
2  Hari   22

'Sita'

In [ ]:
df = pd.DataFrame({
    "Name": ["Ram", "Sita", "Hari"],
    "Age": [25, 30, 22]
})
print(df)
df.iloc[1,1] #it selcts age 1st row and age column andngives op as 30

   Name  Age
0   Ram   25
1  Sita   30
2  Hari   22

np.int64(30)

In [ ]:
df = pd.DataFrame({
    "Name": ["Ram", "Sita", "Hari"],
    "Age": [25, 30, 22]
})
df.iloc[0:2,0:2] #first row and two columns

   Name  Age
0   Ram   25
1  Sita   30

# Boolean Indexing(Filetring)

In [ ]:
#Simple Filter
adults=df[df['Age']>=18]

#Multiple conditions (use & for And, | for OR, wrap in parentheses)
filtered_df=df[(df['Age']>25) & (df['City']=='Banglore')]

#isin() method
cities=['Banglore','Chennai']
eu_users=df[df['City'].isin(cities)]

In [ ]:
df=pd.DataFrame({
    "Name":["Raju","Rani","Navin","Lohit"],
    "Age":[23,34,48,44],
    "City":["Bengalore","Chennai","Bengalore","Hydrabad"]
    })
df
#simple filter
age=df[df['Age'] >= 25]
print(f"\nSimple filter:{age}")

#isin() Method
cities=['Chennai','Bengalore','Kerala'] #we are checking if cities are within the df,so it will print if the given cities or within the df
eu_users=df[df['City'].isin(cities)]
print(f"\n{eu_users}")

# Multiple Conditions
filtered_df=df[(df['Age']>25) & (df["City"]=='Bengalore')]
filtered_df

    Name  Age       City
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore

# Data Cleaning and Handling Missing Values

In [ ]:
# Handling Missinf Data
df.isna().sum()   # Count missing values per column
df_clean=df.drpna() # Drop any row atleast one missing values
df_clean=df.dropna(subset=['City'])  # Drop rows where "City" is missing

#Filling missing values
df_filled= df.fillna(0) # fill nul with 0
df_filled=df['City'].fillna(df['City'].mean()) # Fill with column mean

In [ ]:
# Handling Missing Data(NaN)
s1=pd.Series(["Raju","Rani","Navin","Lohit"])
s2=pd.Series([23,34,48,44,50])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad"])
data=pd.DataFrame({"Name":s1,"Age":s2,"city":s3})
print(data)
Missing=data.isna().sum()
print(Missing)

    Name  Age       city
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad
4    NaN   50        NaN
Name    1
Age     0
city    1
dtype: int64

In [ ]:
s1=pd.Series(["Raju","Rani","Navin","Lohit"])
s2=pd.Series([23,34,48,44,50])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad"])
data=pd.DataFrame({"Name":s1,"Age":s2,"city":s3})
data
df_clean=data.dropna()
df_clean

    Name  Age       city
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad

In [ ]:
s1=pd.Series(["Raju","Rani","Navin","Lohit"])
s2=pd.Series([23,34,48,44,50])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
data
df_clean=data.dropna(subset=['City'])
df_clean

    Name  Age       City
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad

In [ ]:
# Filling Missing Values
s1=pd.Series(["Raju","Rani","Navin","Lohit"])
s2=pd.Series([23,34,48,44,50])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
data
data_filled=data.fillna(0)
data_filled

    Name  Age       City
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad
4      0   50          0

In [ ]:
s1=pd.Series(["Raju","Rani","Navin","Lohit","Raju"])
s2=pd.Series([23,34,48,44])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
print(data)
data_filled=data['Age'].fillna(data['Age'].mean())
data_filled

    Name   Age       City
0   Raju  23.0  Bengalore
1   Rani  34.0    Chennai
2  Navin  48.0  Bengalore
3  Lohit  44.0   Hydrabad
4   Raju   NaN        NaN

0    23.00
1    34.00
2    48.00
3    44.00
4    37.25
Name: Age, dtype: float64

# Duplication Handaling

In [ ]:
df.duplicated().sum()
df_unique=df.drop_duplicates()

In [ ]:
s1=pd.Series(["Raju","Rani","Navin","Lohit","Raju"])
s2=pd.Series([23,34,48,44,23])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad","Bengalore"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
print(data)
duplicates=data.duplicated().sum()
print(duplicates)

    Name  Age       City
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad
4   Raju   23  Bengalore
1

In [ ]:
s1=pd.Series(["Raju","Rani","Navin","Lohit","Raju"])
s2=pd.Series([23,34,48,44,23])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad","Bengalore"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
print(data)
removed=data.drop_duplicates()
print(f"\n{removed}")

    Name  Age       City
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad
4   Raju   23  Bengalore

    Name  Age       City
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad

# Replacing Values

In [ ]:
#df["AGE"]=df["Age"].replace({'Y':'Yes','N':'No'})
df=pd.DataFrame({
    "Name":["Raju","Ravi","Navin"],
    "Status":["Y","N","Y"]
})
print(f"Before replacing:{df}")
#Replace value
df['Status']=df["Status"].replace({'Y':'Yes','N':'No'})
print(f"After replacing:{df}")

Before replacing:    Name Status
0   Raju      Y
1   Ravi      N
2  Navin      Y
After replacing:    Name Status
0   Raju    Yes
1   Ravi     No
2  Navin    Yes

# 6.Data Manuplation & Feature Engineering

Adding, Modifying, Dropping Columns

In [ ]:
# Add new column
#######df["Age_In_Month"]=df["Age"]*12
s1=pd.Series(["Raju","Rani","Navin","Lohit","Raju"])
s2=pd.Series([23,34,48,44,23])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad","Bengalore"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
data["Age_In_Month"]=data["Age"] * 12
data

    Name  Age       City  Age_In_Month
0   Raju   23  Bengalore           276
1   Rani   34    Chennai           408
2  Navin   48  Bengalore           576
3  Lohit   44   Hydrabad           528
4   Raju   23  Bengalore           276

In [ ]:
# Drop Column of Age_In_Month
s1=pd.Series(["Raju","Rani","Navin","Lohit","Raju"])
s2=pd.Series([23,34,48,44,23])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad","Bengalore"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
data["Age_In_Month"]=data["Age"] * 12
data = data.drop("Age_In_Month", axis=1) # main
data

    Name  Age       City
0   Raju   23  Bengalore
1   Rani   34    Chennai
2  Navin   48  Bengalore
3  Lohit   44   Hydrabad
4   Raju   23  Bengalore

In [ ]:
# Rename column
s1=pd.Series(["Raju","Rani","Navin","Lohit","Raju"])
s2=pd.Series([23,34,48,44,23])
s3=pd.Series(["Bengalore","Chennai","Bengalore","Hydrabad","Bengalore"])
data=pd.DataFrame({"Name":s1,"Age":s2,"City":s3})
data=data.rename(columns={'Name': 'Full Name'})
data

  Full Name  Age       City
0      Raju   23  Bengalore
1      Rani   34    Chennai
2     Navin   48  Bengalore
3     Lohit   44   Hydrabad
4      Raju   23  Bengalore

# Applying functions
Use .apply() to execute custom logic row-by-row or column-by-column.

In [ ]:
# Apply to a column
# df["Is_Senior"]=df["Age"].apply(lambda age: True if age >=60 else False)
data=pd.DataFrame({
    "Name":['Ram','Ravi','Praveen','Lohith','Monisha','Pavan','Chanz'],
    "Age":[23,54,23,60,40,50,61],
    "City":['Bengalore','Chennai','Hyderabad','Bengalore','Hyderabad','Hyderabad','Bengalore']
})
data["Is_Senior"]=data["Age"].apply(lambda age: True if age>=60 else False)

      Name  Age       City  Is_Senior
0      Ram   23  Bengalore      False
1     Ravi   54    Chennai      False
2  Praveen   23  Hyderabad      False
3   Lohith   60  Bengalore       True
4  Monisha   40  Hyderabad      False
5    Pavan   50  Hyderabad      False
6    Chanz   61  Bengalore       True

In [ ]:
# Vectorized methods
df["Upper_Name"]=df["Name"].str.upper()
df["fisrt_Name"]=df["Name"].str.split(' ').str[0]

In [ ]:
df=pd.DataFrame({
    "Name":['Ram','Ravi','Praveen','Lohith','Monisha','Pavan','Chanz']
})
df["Upper_Name"]=df["Name"].str.upper()
df

      Name Upper_Name
0      Ram        RAM
1     Ravi       RAVI
2  Praveen    PRAVEEN
3   Lohith     LOHITH
4  Monisha    MONISHA
5    Pavan      PAVAN
6    Chanz      CHANZ

In [ ]:
df=pd.DataFrame({
    "Name":['Ram Raj','Ravi sharma','Praveen kumar','Lohith Das','Monisha Singh','Pavan Sai','Chanz Robert']
})
df["First_Name"]=df["Name"].str.split(' ').str[0] # str[0] o is like first index
df

            Name First_Name
0        Ram Raj        Ram
1    Ravi sharma       Ravi
2  Praveen kumar    Praveen
3     Lohith Das     Lohith
4  Monisha Singh    Monisha
5      Pavan Sai      Pavan
6   Chanz Robert      Chanz

In [ ]:
df=pd.DataFrame({
    "Name":['Ram Raj','Ravi sharma','Praveen kumar','Lohith Das','Monisha Singh','Pavan Sai','Chanz Robert']
})
df["Last_Name"]=df["Name"].str.split(' ').str[1] # str[1] is second word as index 1
df

            Name Last_Name
0        Ram Raj       Raj
1    Ravi sharma    sharma
2  Praveen kumar     kumar
3     Lohith Das       Das
4  Monisha Singh     Singh
5      Pavan Sai       Sai
6   Chanz Robert    Robert

# 7. Grouping and Aggrigation(groupby)
Splitting data into groups, applying a function, and combining the results Equivalent to SQL (Group By)

In [ ]:
#SIMPLE GROUPINGS
# mean_age=df.groupby('City')['Age'].mean()
data=pd.DataFrame({
    "Name":['Ram','Ravi','Praveen','Lohith','Monisha','Pavan','Chanz'],
    "Age":[23,45,23,22,40,50,59],
    "City":['Bengalore','Chennai','Hyderabad','Bengalore','Hyderabad','Hyderabad','Bengalore']
})
mean_age=data.groupby("City")["Age"].mean() # main 
mean_age

City
Bengalore    34.666667
Chennai      45.000000
Hyderabad    37.666667
Name: Age, dtype: float64

In [ ]:
# Multiple basic aggregations
summary=df.groupby("City")["Age"].agg(["mean","max","min","count"])

In [ ]:
data=pd.DataFrame({
    "Name":['Ram','Ravi','Praveen','Lohith','Monisha','Pavan','Chanz'],
    "Age":[23,45,23,22,40,50,59],
    "City":['Bengalore','Chennai','Hyderabad','Bengalore','Hyderabad','Hyderabad','Bengalore']
})
multiple_agg=data.groupby("City")["Age"].agg(["mean","max","min","count"]) # main
multiple_agg

                mean  max  min  count
City
Bengalore  34.666667   59   22      3
Chennai    45.000000   45   45      1
Hyderabad  37.666667   50   23      3

In [ ]:
# Complex aggregations on different columns
agg_dict={
    "Age":"mean",
    "Salary":['sum','max']
}
complex_summary=df.groupby("City").agg(agg_dict)

In [ ]:
data=pd.DataFrame({
    "Name":['Ram','Ravi','Praveen','Lohith','Monisha','Pavan','Chanz'],
    "Age":[23,45,23,22,40,50,59],
    "City":['Bengalore','Chennai','Hyderabad','Bengalore','Hyderabad','Hyderabad','Bengalore'],
    "Salary":[200,300,400,200,400,500,1000]
})
agg_dict={
    "Age":'mean',
    "Salary":['sum','max','min']
    }
complex_summary= data.groupby("City").agg(agg_dict)
complex_summary

                 Age Salary
                mean    sum   max  min
City
Bengalore  34.666667   1400  1000  200
Chennai    45.000000    300   300  300
Hyderabad  37.666667   1300   500  400

# Pivot Table
Craetes spreadsheets-style pivot tables

In [ ]:
pivot = pd.pivot_table(
    df, 
    values='Salary', 
    index='City', 
    columns='Department', 
    aggfunc=np.mean, 
    fill_value=0
)

In [ ]:
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "City": ["Bangalore", "Bangalore", "Chennai", "Chennai", "Bangalore", "Chennai"],
    "Department": ["HR", "IT", "HR", "IT", "HR", "IT"],
    "Salary": [30000, 40000, 35000, 45000, 32000, 48000]
})
df
pivot = pd.pivot_table(
    df, 
    values='Salary', 
    index='City', 
    columns='Department', 
    aggfunc=np.mean, 
    fill_value=0
)
pivot

C:\Users\venur\AppData\Local\Temp\ipykernel_12576\1596352662.py:8: FutureWarning: The provided callable <function mean at 0x000002DC21C651C0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot = pd.pivot_table(

Department       HR       IT
City
Bangalore   31000.0  40000.0
Chennai     35000.0  46500.0

# 8.Combining DataFrames
Ewuivalent to SQL JOINs and UNIONs

Concatenation (UNIONs)

Stacking DataFrames vertically or horizontally

In [ ]:
# Vertically (stacking rows)
df_combined=pd.concat([df1,df2],axis=0)

# Horizonatlly (side-by-side)
df_side=pd.concat([df1,df2],axis=1)

In [ ]:
# Vertically (stacking rows)
df1=pd.DataFrame({
    'Name':['Ravi','Raju','Sukanya'],
    'Age':[12,13,12]
})

df2=pd.DataFrame({
    'Name':['Ram','Sharath','Isha'],
    'Age':[14,11,10]
})
vertical_combine = pd.concat([df1,df2],axis=0)
vertical_combine

      Name  Age
0     Ravi   12
1     Raju   13
2  Sukanya   12
0      Ram   14
1  Sharath   11
2     Isha   10

In [ ]:
df1=pd.DataFrame({
    'Name':['Ravi','Raju','Sukanya'],
    'Age':[12,13,12]
})

df2=pd.DataFrame({
    'Name':['Ram','Sharath','Isha'],
    'Age':[14,11,10]
})
hori_combine = pd.concat([df1,df2],axis=1)
hori_combine

      Name  Age     Name  Age
0     Ravi   12      Ram   14
1     Raju   13  Sharath   11
2  Sukanya   12     Isha   10

# Merging (JOIN)
Connecting related DataFrames based on keys.

In [ ]:
# Inner Join
merged_df = pd.merge(users_df, orders_df, on='user_id', how='inner')

# Left Join
merged_left = pd.merge(users_df, orders_df, left_on='id', right_on='user_id', how='left')
# how parameter accepts: 'left', 'right', 'outer', 'inner'.

In [ ]:
# Inner Join
user_df=pd.DataFrame({
    'user_id':[1,2,3],
    'Name':['Ravi','Pavan','Venkat']
})
order_df=pd.DataFrame({
    'user_id':[1,2,4],
    'Order':['Laptop','Mobile','Tablet']
})
merged_df=pd.merge(user_df, order_df, on='user_id', how='inner')
merged_df

   user_id   Name   Order
0        1   Ravi  Laptop
1        2  Pavan  Mobile

In [ ]:
# Left Join
user_df=pd.DataFrame({
    'id':[1,2,3],
    'Name':['Ravi','Pavan','Venkat']
})
order_df=pd.DataFrame({
    'user_id':[1,2,4],
    'Order':['Laptop','Mobile','Tablet']
})
left_join=pd.merge(user_df,order_df, left_on='id',right_on='user_id',how='left')
left_join

   id    Name  user_id   Order
0   1    Ravi      1.0  Laptop
1   2   Pavan      2.0  Mobile
2   3  Venkat      NaN     NaN

how parameter accepts: 'left', 'right', 'outer', 'inner'.

# 9.Time Series Data Handling

Pandas excels at handling dates and time

In [47]:
# Convert strings to datetime objects
df['Date']=pd.to_datetime(df['Date_String'])

# extract components
df['Year']=df['Date'].dt.year
df['Month']=df['Date'].dt.month
df['DayOfWeek']=df['Date'].dt.day_name()

# Setting datetime as index allows for powerful time slicing and resampling
df.set_index('Date', inplace=True)
df.loc['2023-01'] #Selects all rows in Jan 2023

# Resampling (e.g., converting daily data to monthly sum)
monthly_revenue=df['Revenue'].resample('M').sum()

C:\Users\venur\AppData\Local\Temp\ipykernel_25440\2267565364.py:14: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_revenue=df['Revenue'].resample('M').sum()

In [49]:
df=pd.DataFrame({
    "Date_String": ["2023-01-01", "2023-01-15", "2023-02-10", "2023-02-20"],
    "Revenue": [100, 200, 150, 250]
})
df['Date']=pd.to_datetime(df['Date_String'])#it creates another column name Date in dattime formate
df['Year']=df['Date'].dt.year
df['Month']=df['Date'].dt.month
df['DayOfWeek']=df['Date'].dt.day_name()
df.set_index('Date',inplace=True)
df.loc['2023-01']
monthly_revenue=df['Revenue'].resample('ME').sum()
print(monthly_revenue)
print(df)

Date
2023-01-31    300
2023-02-28    400
Freq: ME, Name: Revenue, dtype: int64
           Date_String  Revenue  Year  Month DayOfWeek
Date
2023-01-01  2023-01-01      100  2023      1    Sunday
2023-01-15  2023-01-15      200  2023      1    Sunday
2023-02-10  2023-02-10      150  2023      2    Friday
2023-02-20  2023-02-20      250  2023      2    Monday